package app2;

import static java.awt.Color.black;
import static java.awt.Color.white;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import javax.swing.JOptionPane;

//@author MarcoVilera
public class Eval2 extends javax.swing.JFrame {

    public Eval2() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        entryLabel = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        nEntry = new javax.swing.JTextField();
        separatorN = new javax.swing.JSeparator();
        mEntry = new javax.swing.JTextField();
        separatorM = new javax.swing.JSeparator();
        calcBtn = new javax.swing.JPanel();
        calcLabel = new javax.swing.JLabel();
        clrBtn = new javax.swing.JPanel();
        clrLabel = new javax.swing.JLabel();
        opLabel = new javax.swing.JLabel();
        dotOp1 = new javax.swing.JLabel();
        op1Display = new javax.swing.JLabel();
        shownOp1 = new javax.swing.JLabel();
        dotOp2 = new javax.swing.JLabel();
        op2Display = new javax.swing.JLabel();
        scrollOp2 = new javax.swing.JScrollPane();
        shownOp2 = new javax.swing.JTextArea();
        dotOp3 = new javax.swing.JLabel();
        op3Display = new javax.swing.JLabel();
        scrollOp3 = new javax.swing.JScrollPane();
        shownOp3 = new javax.swing.JTextArea();
        dotOp4 = new javax.swing.JLabel();
        op4Display = new javax.swing.JLabel();
        scrollOp4 = new javax.swing.JScrollPane();
        shownOp4 = new javax.swing.JTextArea();
        dotOp5 = new javax.swing.JLabel();
        op5Display = new javax.swing.JLabel();
        shownOp5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(900, 680));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entryLabel.setText("Entrada de Datos");
        bg.add(entryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        mLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLabel.setText("Valor M");
        bg.add(mLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 140, -1));

        nLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nLabel.setText("Valor N ");
        bg.add(nLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 140, -1));

        nEntry.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nEntry.setForeground(new java.awt.Color(153, 153, 153));
        nEntry.setText("Introduce el valor de N");
        nEntry.setBorder(null);
        nEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nEntryMousePressed(evt);
            }
        });
        nEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEntryActionPerformed(evt);
            }
        });
        bg.add(nEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 140, 30));

        separatorN.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separatorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 140, 20));

        mEntry.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        mEntry.setForeground(new java.awt.Color(153, 153, 153));
        mEntry.setText("Introduce el valor de M");
        mEntry.setBorder(null);
        mEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mEntryMousePressed(evt);
            }
        });
        mEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEntryActionPerformed(evt);
            }
        });
        bg.add(mEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 140, 30));

        separatorM.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(separatorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 140, 20));

        calcBtn.setBackground(new java.awt.Color(0, 150, 136));
        calcBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        calcLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        calcLabel.setForeground(new java.awt.Color(255, 255, 255));
        calcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcLabel.setText("Calcular");
        calcLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout calcBtnLayout = new javax.swing.GroupLayout(calcBtn);
        calcBtn.setLayout(calcBtnLayout);
        calcBtnLayout.setHorizontalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        calcBtnLayout.setVerticalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(calcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 110, 30));

        clrBtn.setBackground(new java.awt.Color(0, 150, 136));
        clrBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        clrLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clrLabel.setForeground(new java.awt.Color(255, 255, 255));
        clrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clrLabel.setText("Limpiar");
        clrLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clrLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clrLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout clrBtnLayout = new javax.swing.GroupLayout(clrBtn);
        clrBtn.setLayout(clrBtnLayout);
        clrBtnLayout.setHorizontalGroup(
            clrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(clrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clrBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(clrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        clrBtnLayout.setVerticalGroup(
            clrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(clrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clrBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(clrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(clrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 110, 30));

        opLabel.setBackground(new java.awt.Color(255, 255, 255));
        opLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opLabel.setForeground(new java.awt.Color(255, 255, 255));
        opLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opLabel.setText("Operaciones");
        bg.add(opLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1000, -1));

        dotOp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dotOp1.setForeground(new java.awt.Color(255, 255, 255));
        dotOp1.setText("•");
        bg.add(dotOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        op1Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op1Display.setForeground(new java.awt.Color(255, 255, 255));
        op1Display.setText("Comprobar si M es un número primo:");
        bg.add(op1Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        shownOp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shownOp1.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(shownOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        dotOp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dotOp2.setForeground(new java.awt.Color(255, 255, 255));
        dotOp2.setText("•");
        bg.add(dotOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        op2Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op2Display.setForeground(new java.awt.Color(255, 255, 255));
        op2Display.setText("Potencia N^M:");
        bg.add(op2Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        scrollOp2.setBorder(null);

        shownOp2.setEditable(false);
        shownOp2.setColumns(20);
        shownOp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shownOp2.setLineWrap(true);
        shownOp2.setRows(1);
        shownOp2.setBorder(null);
        scrollOp2.setViewportView(shownOp2);

        bg.add(scrollOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 730, 40));

        dotOp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dotOp3.setForeground(new java.awt.Color(255, 255, 255));
        dotOp3.setText("•");
        bg.add(dotOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        op3Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op3Display.setForeground(new java.awt.Color(255, 255, 255));
        op3Display.setText("Sucesión de Fibonacci hasta que sea <=|NxM|:");
        bg.add(op3Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        scrollOp3.setBorder(null);

        shownOp3.setEditable(false);
        shownOp3.setColumns(20);
        shownOp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shownOp3.setLineWrap(true);
        shownOp3.setRows(1);
        shownOp3.setBorder(null);
        scrollOp3.setViewportView(shownOp3);

        bg.add(scrollOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 550, 20));

        dotOp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dotOp4.setForeground(new java.awt.Color(255, 255, 255));
        dotOp4.setText("•");
        bg.add(dotOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        op4Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op4Display.setForeground(new java.awt.Color(255, 255, 255));
        op4Display.setText("Factorial de N:");
        bg.add(op4Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        scrollOp4.setBorder(null);

        shownOp4.setEditable(false);
        shownOp4.setColumns(20);
        shownOp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shownOp4.setLineWrap(true);
        shownOp4.setRows(1);
        shownOp4.setBorder(null);
        scrollOp4.setViewportView(shownOp4);

        bg.add(scrollOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 740, 40));

        dotOp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dotOp5.setForeground(new java.awt.Color(255, 255, 255));
        dotOp5.setText("•");
        bg.add(dotOp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        op5Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op5Display.setForeground(new java.awt.Color(255, 255, 255));
        op5Display.setText("Suma de los digitos |NxM|:");
        bg.add(op5Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        shownOp5.setBackground(new java.awt.Color(255, 255, 255));
        shownOp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shownOp5.setForeground(new java.awt.Color(255, 255, 255));
        shownOp5.setText("xddd");
        bg.add(shownOp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nEntryActionPerformed

    private void mEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEntryActionPerformed
    //Botón Calcular
    private void calcLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcLabelMouseEntered
        //Cambia de color cuando el mouse entra a botón
        calcBtn.setBackground(new java.awt.Color(0, 105, 92));
    }//GEN-LAST:event_calcLabelMouseEntered

    private void calcLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcLabelMouseExited
        //Cambia de color cuando el mouse sale del botón
        calcBtn.setBackground(new java.awt.Color(0, 150, 136));
    }//GEN-LAST:event_calcLabelMouseExited
    //Valores Maximos y Minimos
    int NMAXIMO = 100;
    int NMIN = -100;

    private void calcLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcLabelMouseClicked
        //Acciones cuando se presiona el botón "Calcular"
        int n = 0;
        int m = 0;
        BigDecimal nd;
        BigInteger nnd;
        boolean fail = false;

        try {
            n = Integer.parseInt(nEntry.getText());
            if (n <= NMIN || n >= NMAXIMO) {
                throw new NumException();
            }
        } catch (NumberFormatException errorEntry) {
            JOptionPane.showMessageDialog(null, "Valor N Invalido, introduzca un valor númerico");
            nEntry.setText("Introduce el valor de N");
            nEntry.setForeground(new java.awt.Color(153, 153, 153));
            fail = true;
        } catch (NumException nmInvalid) {
            JOptionPane.showMessageDialog(null, "Valor N Invalido, Introduzca un número entre -99 y 99");
            nEntry.setText("Introduce el valor de N");
            nEntry.setForeground(new java.awt.Color(153, 153, 153));
            fail = true;
        }

        try {
            m = Integer.parseInt(mEntry.getText());
            if (m <= NMIN || m >= NMAXIMO) {
                throw new NumException();
            }
        } catch (NumberFormatException errorEntry) {
            JOptionPane.showMessageDialog(null, "Valor M Invalido, introduzca un valor númerico");
            mEntry.setText("Introduce el valor de M");
            mEntry.setForeground(new java.awt.Color(153, 153, 153));
            fail = true;
        } catch (NumException nmInvalid) {
            JOptionPane.showMessageDialog(null, "Valor M Invalido, Introduzca un número entre -99 y 99");
            mEntry.setText("Introduce el valor de M");
            mEntry.setForeground(new java.awt.Color(153, 153, 153));
            fail = true;
        }

        nd = BigDecimal.valueOf(n);
        nnd = BigInteger.valueOf(n);
        int nm = n * m;
        if (nm < 0) {
            nm = nm * -1;
        }
        //Condicional de mostrar efectuar/operaciones
        if (fail == false) {
            //Titulo Operaciones
            opLabel.setForeground(black);

            //Operación 1
            dotOp1.setForeground(new java.awt.Color(0, 77, 64));
            op1Display.setForeground(black);

            if (OperacionesVentana.esPrimo(m)) {
                shownOp1.setForeground(black);
                shownOp1.setText("El número " + m + " es primo");
            } else if (OperacionesVentana.esPrimo(m) == false && m < 0) {
                shownOp1.setForeground(black);
                shownOp1.setText("Los números negativos no pueden ser primos");
            } else {
                shownOp1.setForeground(black);
                shownOp1.setText("El número " + m + " no es primo");
            }

            //Operación 2
            dotOp2.setForeground(new java.awt.Color(0, 77, 64));
            op2Display.setForeground(black);
            shownOp2.setForeground(black);
            shownOp2.setText(OperacionesVentana.potRecur(nd, m).toString());

            //Operación 3
            dotOp3.setForeground(new java.awt.Color(0, 77, 64));
            op3Display.setForeground(black);
            ArrayList<Integer> vector = new ArrayList<>();
            OperacionesVentana.fibonacciRecur(nm, vector, 0);
            shownOp3.setForeground(black);
            String text;
            text = OperacionesVentana.vectorToString(vector);
            shownOp3.setText(text);

            //Operación 4
            dotOp4.setForeground(new java.awt.Color(0, 77, 64));
            op4Display.setForeground(black);
            if (n < 0) {
                shownOp4.setForeground(black);
                shownOp4.setText("No se puede obtener el factorial de un número negativo");
            } else {
                shownOp4.setForeground(black);
                shownOp4.setText(OperacionesVentana.factoRecur(nnd).toString());
            }

            //Operación 5
            dotOp5.setForeground(new java.awt.Color(0, 77, 64));
            op5Display.setForeground(black);
            shownOp5.setForeground(black);
            shownOp5.setText(Integer.toString(nm) + "=" + Integer.toString(OperacionesVentana.sumDigit(nm)));
        }

    }//GEN-LAST:event_calcLabelMouseClicked
    //Fin Botón Calcular

    //Botón Limpiar
    private void clrLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrLabelMouseEntered
        clrBtn.setBackground(new java.awt.Color(0, 105, 92));
    }//GEN-LAST:event_clrLabelMouseEntered

    private void clrLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrLabelMouseExited
        clrBtn.setBackground(new java.awt.Color(0, 150, 136));
    }//GEN-LAST:event_clrLabelMouseExited

    private void clrLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrLabelMouseClicked
        //Titulo Operaciones
        opLabel.setForeground(white);

        //Operación 1
        dotOp1.setForeground(white);
        op1Display.setForeground(white);
        shownOp1.setText("");

        //Operación 2
        dotOp2.setForeground(white);
        op2Display.setForeground(white);
        shownOp2.setText("");

        //Operación 3
        dotOp3.setForeground(white);
        op3Display.setForeground(white);
        shownOp3.setText("");

        //Operación 4
        dotOp4.setForeground(white);
        op4Display.setForeground(white);
        shownOp4.setText("");

        //Operación 5
        dotOp5.setForeground(white);
        op5Display.setForeground(white);
        shownOp5.setText("");

        //Entrada de texto de N
        nEntry.setText("Introduce el valor de N");
        nEntry.setForeground(new java.awt.Color(153, 153, 153));

        //Entrada de texto de M
        mEntry.setText("Introduce el valor de M");
        mEntry.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_clrLabelMouseClicked
    //Fin Botón Limpiar

    private void nEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nEntryMousePressed

        if (nEntry.getText().equals("Introduce el valor de N")) {
            nEntry.setText("");
            nEntry.setForeground(black);
        }
        if (mEntry.getText().isEmpty()) {
            mEntry.setText("Introduce el valor de M");
            mEntry.setForeground(new java.awt.Color(153, 153, 153));
        }

    }//GEN-LAST:event_nEntryMousePressed

    private void mEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEntryMousePressed

        if (mEntry.getText().equals("Introduce el valor de M")) {
            mEntry.setText("");
            mEntry.setForeground(black);
        }

        if (nEntry.getText().isEmpty()) {
            nEntry.setText("Introduce el valor de N");
            nEntry.setForeground(new java.awt.Color(153, 153, 153));
        }

    }//GEN-LAST:event_mEntryMousePressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eval2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eval2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eval2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eval2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eval2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel calcBtn;
    private javax.swing.JLabel calcLabel;
    private javax.swing.JPanel clrBtn;
    private javax.swing.JLabel clrLabel;
    private javax.swing.JLabel dotOp1;
    private javax.swing.JLabel dotOp2;
    private javax.swing.JLabel dotOp3;
    private javax.swing.JLabel dotOp4;
    private javax.swing.JLabel dotOp5;
    private javax.swing.JLabel entryLabel;
    private javax.swing.JTextField mEntry;
    private javax.swing.JLabel mLabel;
    private javax.swing.JTextField nEntry;
    private javax.swing.JLabel nLabel;
    private javax.swing.JLabel op1Display;
    private javax.swing.JLabel op2Display;
    private javax.swing.JLabel op3Display;
    private javax.swing.JLabel op4Display;
    private javax.swing.JLabel op5Display;
    private javax.swing.JLabel opLabel;
    private javax.swing.JScrollPane scrollOp2;
    private javax.swing.JScrollPane scrollOp3;
    private javax.swing.JScrollPane scrollOp4;
    private javax.swing.JSeparator separatorM;
    private javax.swing.JSeparator separatorN;
    private javax.swing.JLabel shownOp1;
    private javax.swing.JTextArea shownOp2;
    private javax.swing.JTextArea shownOp3;
    private javax.swing.JTextArea shownOp4;
    private javax.swing.JLabel shownOp5;
    // End of variables declaration//GEN-END:variables
}
