package app3;

//@author MarcoVilera
import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.GRAY;
import static java.awt.Color.WHITE;

public class Eval3 extends javax.swing.JFrame {

    // Botón continuar presionado
    boolean pressed = false;
    //Botón agregar presionado
    boolean aggPressed = false;
    //Datos ya mostrados
    boolean mostrados = false;
    boolean mostradoGet = true;
    boolean mostradosFin = true;
    ListaEnlazada lista1 = new ListaEnlazada();
    ListaEnlazada lista2 = new ListaEnlazada();
    ListaEnlazada lista3 = new ListaEnlazada();
    //Creates new form Ventana

    public Eval3() {
        initComponents();
        background.requestFocusInWindow();

        /*//Elementos invisibles al inicio
        elementAddedLabel.setText("Elemento Agregado");
        elementAddedLabel.setVisible(false);

        getElementLabel.setVisible(false);
        getElementEntry.setVisible(false);
        separatorgetElement.setVisible(false);
        btnObtener.setVisible(false);

        deleteElementLabel.setVisible(false);
        deleteElementEntry.setVisible(false);
        separatorDeleteElement.setVisible(false);
        btnDeleteElement.setVisible(false);

        labelSortMay.setVisible(false);
        labelSortMen.setVisible(false);*/
        clear();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        labelEntrada = new javax.swing.JLabel();
        entryField = new javax.swing.JTextField();
        separatorEntry = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JPanel();
        btnTextAgregar = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JPanel();
        btnTextContinuar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        btnTextLimpiar = new javax.swing.JLabel();
        elementAddedLabel = new javax.swing.JLabel();
        listDisplay = new javax.swing.JScrollPane();
        listDisplayText = new javax.swing.JTextArea();
        getElementLabel = new javax.swing.JLabel();
        getElementEntry = new javax.swing.JTextField();
        separatorgetElement = new javax.swing.JSeparator();
        btnObtener = new javax.swing.JPanel();
        btnTextObtener = new javax.swing.JLabel();
        dsplayGetElement = new javax.swing.JLabel();
        deleteElementLabel = new javax.swing.JLabel();
        deleteElementEntry = new javax.swing.JTextField();
        separatorDeleteElement = new javax.swing.JSeparator();
        btnDeleteElement = new javax.swing.JPanel();
        btnTextDeleteElement = new javax.swing.JLabel();
        dsplayDeleteElement = new javax.swing.JLabel();
        labelSortMay = new javax.swing.JLabel();
        labelSortMen = new javax.swing.JLabel();
        dsplaySortMay = new javax.swing.JScrollPane();
        dsplaySortMayText = new javax.swing.JTextArea();
        dsplaySortMen = new javax.swing.JScrollPane();
        dsplaySortMenText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(0, 0, 0));
        background.setPreferredSize(new java.awt.Dimension(850, 570));
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEntrada.setForeground(new java.awt.Color(0, 0, 0));
        labelEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEntrada.setText("Entrada de datos");
        background.add(labelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, -1));

        entryField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entryField.setForeground(java.awt.Color.gray);
        entryField.setText("Ingresa un número");
        entryField.setBorder(null);
        entryField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entryFieldMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryFieldMousePressed(evt);
            }
        });
        entryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryFieldActionPerformed(evt);
            }
        });
        background.add(entryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 130, -1));

        separatorEntry.setForeground(java.awt.Color.black);
        background.add(separatorEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, 10));

        btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTextAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTextAgregar.setForeground(java.awt.Color.gray);
        btnTextAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextAgregar.setText("Agregar");
        btnTextAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTextAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnTextAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnTextAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 116, 30));

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTextContinuar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTextContinuar.setForeground(java.awt.Color.gray);
        btnTextContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextContinuar.setText("Continuar");
        btnTextContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextContinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextContinuarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnContinuarLayout = new javax.swing.GroupLayout(btnContinuar);
        btnContinuar.setLayout(btnContinuarLayout);
        btnContinuarLayout.setHorizontalGroup(
            btnContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnContinuarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTextContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnContinuarLayout.setVerticalGroup(
            btnContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnContinuarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTextContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setForeground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTextLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTextLimpiar.setForeground(java.awt.Color.gray);
        btnTextLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextLimpiar.setText("Limpiar");
        btnTextLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTextLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 116, 30));

        elementAddedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        elementAddedLabel.setForeground(new java.awt.Color(0, 0, 0));
        elementAddedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elementAddedLabel.setText("Elemento Agregado");
        background.add(elementAddedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1000, -1));

        listDisplay.setBorder(null);
        listDisplay.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listDisplayText.setEditable(false);
        listDisplayText.setColumns(20);
        listDisplayText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listDisplayText.setRows(5);
        listDisplay.setViewportView(listDisplayText);

        background.add(listDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 250, 40));

        getElementLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getElementLabel.setForeground(new java.awt.Color(0, 0, 0));
        getElementLabel.setText("Obtener elemento por su posición");
        background.add(getElementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        getElementEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getElementEntry.setForeground(java.awt.Color.gray);
        getElementEntry.setBorder(null);
        getElementEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                getElementEntryMousePressed(evt);
            }
        });
        getElementEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getElementEntryActionPerformed(evt);
            }
        });
        background.add(getElementEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, -1));

        separatorgetElement.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separatorgetElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 10));

        btnObtener.setBackground(new java.awt.Color(0, 150, 136));
        btnObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTextObtener.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTextObtener.setForeground(new java.awt.Color(255, 255, 255));
        btnTextObtener.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextObtener.setText("Obtener");
        btnTextObtener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextObtenerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextObtenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextObtenerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnObtenerLayout = new javax.swing.GroupLayout(btnObtener);
        btnObtener.setLayout(btnObtenerLayout);
        btnObtenerLayout.setHorizontalGroup(
            btnObtenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextObtener, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnObtenerLayout.setVerticalGroup(
            btnObtenerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextObtener, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(btnObtener, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 80, -1));

        dsplayGetElement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background.add(dsplayGetElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        deleteElementLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteElementLabel.setForeground(new java.awt.Color(0, 0, 0));
        deleteElementLabel.setText("Eliminar un elemento");
        background.add(deleteElementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        deleteElementEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteElementEntry.setForeground(java.awt.Color.gray);
        deleteElementEntry.setToolTipText("");
        deleteElementEntry.setBorder(null);
        deleteElementEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteElementEntryMousePressed(evt);
            }
        });
        deleteElementEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteElementEntryActionPerformed(evt);
            }
        });
        background.add(deleteElementEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 120, -1));

        separatorDeleteElement.setForeground(new java.awt.Color(0, 0, 0));
        background.add(separatorDeleteElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, 10));

        btnDeleteElement.setBackground(new java.awt.Color(0, 150, 136));

        btnTextDeleteElement.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTextDeleteElement.setForeground(new java.awt.Color(255, 255, 255));
        btnTextDeleteElement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTextDeleteElement.setText("Eliminar");
        btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTextDeleteElement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTextDeleteElementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTextDeleteElementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTextDeleteElementMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDeleteElementLayout = new javax.swing.GroupLayout(btnDeleteElement);
        btnDeleteElement.setLayout(btnDeleteElementLayout);
        btnDeleteElementLayout.setHorizontalGroup(
            btnDeleteElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextDeleteElement, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnDeleteElementLayout.setVerticalGroup(
            btnDeleteElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTextDeleteElement, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(btnDeleteElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 80, 30));

        dsplayDeleteElement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dsplayDeleteElement.setToolTipText("");
        background.add(dsplayDeleteElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        labelSortMay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSortMay.setForeground(new java.awt.Color(0, 0, 0));
        labelSortMay.setText("Elementos ordenados de mayor a menor");
        background.add(labelSortMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        labelSortMen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSortMen.setForeground(new java.awt.Color(0, 0, 0));
        labelSortMen.setText("Elementos ordenados de menor a mayor");
        background.add(labelSortMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        dsplaySortMay.setBorder(null);
        dsplaySortMay.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        dsplaySortMayText.setEditable(false);
        dsplaySortMayText.setColumns(20);
        dsplaySortMayText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dsplaySortMayText.setRows(5);
        dsplaySortMay.setViewportView(dsplaySortMayText);

        background.add(dsplaySortMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 250, 40));

        dsplaySortMen.setBorder(null);
        dsplaySortMen.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        dsplaySortMenText.setEditable(false);
        dsplaySortMenText.setColumns(20);
        dsplaySortMenText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dsplaySortMenText.setRows(5);
        dsplaySortMen.setViewportView(dsplaySortMenText);

        background.add(dsplaySortMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryFieldActionPerformed

    private void getElementEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getElementEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getElementEntryActionPerformed

    private void deleteElementEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteElementEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteElementEntryActionPerformed

    //Botón Agregar cuando el mouse entre
    private void btnTextAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextAgregarMouseEntered
        String inputUsr = entryField.getText();
        boolean esValido = !("Ingresa un número".equals(inputUsr)) && !("".equals(inputUsr));

        if ((esValido) || aggPressed && !mostrados) {
            btnTextAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnAgregar.setBackground(new java.awt.Color(0, 121, 107));
            btnTextAgregar.setForeground(WHITE);
        } else {
            btnTextAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
            btnTextAgregar.setForeground(GRAY);
        }
    }//GEN-LAST:event_btnTextAgregarMouseEntered

    //Botón Agregar cuando el mouse sale
    private void btnTextAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextAgregarMouseExited
        String inputUsr = entryField.getText();
        boolean esValido = !("Ingresa un número".equals(inputUsr)) && !("".equals(inputUsr));

        if ((esValido) || aggPressed && !mostrados) {
            btnAgregar.setBackground(new java.awt.Color(0, 150, 136));
            btnTextAgregar.setForeground(WHITE);
        }
    }//GEN-LAST:event_btnTextAgregarMouseExited

    //Botón Agregar al ser clickeado
    //TODO MODIFICAR IF NO MUESTRA elementAddedLabel
    private void btnTextAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextAgregarMouseClicked
        background.requestFocusInWindow();
        String inputUsr = entryField.getText();
        boolean esValido = !("Ingresa un número".equals(inputUsr)) && !("".equals(inputUsr));

        //if (esValido) {
        try {
            int n;
            n = Integer.parseInt(inputUsr);
            lista1.addFirst(n);
            lista2.addFirst(n);
            lista3.addFirst(n);
            entryField.setText("Ingresa un número");
            entryField.setForeground(GRAY);
            elementAddedLabel.setVisible(true);
            elementAddedLabel.setText("Elemento agregado");
            aggPressed = true;
            btnContinuar.setBackground(new java.awt.Color(0, 150, 136));
            btnTextContinuar.setForeground(WHITE);

        } catch (NumberFormatException valueNotValid) {
            elementAddedLabel.setVisible(true);
            elementAddedLabel.setText("Valor no valido");
        }
        //}
    }//GEN-LAST:event_btnTextAgregarMouseClicked

    //Botón Continuar cuando el mouse entre
    private void btnTextContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextContinuarMouseEntered
        if (!aggPressed || mostrados) {
            btnTextContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnContinuar.setBackground(new Color(204, 204, 204));
            btnTextContinuar.setForeground(GRAY);
        } else {
            btnContinuar.setBackground(new java.awt.Color(0, 121, 107));
            btnTextContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_btnTextContinuarMouseEntered

    //Botón Continuar cuando el mouse sale
    private void btnTextContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextContinuarMouseExited
        if (!aggPressed || mostrados) {
            btnContinuar.setBackground(new Color(204, 204, 204));
        } else {
            btnContinuar.setBackground(new Color(0, 150, 136));
        }
    }//GEN-LAST:event_btnTextContinuarMouseExited

    //Botón Continuar al ser clickeado
    private void btnTextContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextContinuarMouseClicked
        background.requestFocusInWindow();
        if (aggPressed && !mostrados) {
            pressed = true;
            mostrados = true;
            btnLimpiar.setBackground(new java.awt.Color(0, 150, 136));
            btnTextLimpiar.setForeground(WHITE);

            elementAddedLabel.setText("Lista Generada");

            getElementLabel.setVisible(true);
            getElementEntry.setVisible(true);
            separatorgetElement.setVisible(true);
            btnObtener.setVisible(true);

            deleteElementLabel.setVisible(true);
            deleteElementEntry.setVisible(true);
            separatorDeleteElement.setVisible(true);
            btnDeleteElement.setVisible(true);

            Nodo actual = lista1.head;

            while (actual != null) {

                int valor = actual.getValor();
                listDisplayText.append(Integer.toString(valor) + " ");
                actual = actual.getSiguiente();

            }

            entryField.setText("Ingresa un número");
            entryField.setForeground(Color.GRAY);
            entryField.setEditable(false);

            btnAgregar.setBackground(new Color(204, 204, 204));
            btnTextAgregar.setForeground(Color.GRAY);
            btnContinuar.setBackground(new Color(204, 204, 204));
            btnTextContinuar.setForeground(Color.GRAY);

            getElementLabel.setText("Obtener elemento por su posición");
            getElementEntry.setText("Ingresa la posición");
            getElementEntry.setForeground(Color.GRAY);
            separatorgetElement.setForeground(Color.BLACK);
            btnObtener.setBackground(new Color(0, 150, 136));

            deleteElementLabel.setText("Eliminar un elemento");
            deleteElementEntry.setText("Ingresa la posición");
            separatorDeleteElement.setForeground(Color.BLACK);
            btnDeleteElement.setBackground(new Color(0, 150, 136));
        }
    }//GEN-LAST:event_btnTextContinuarMouseClicked

    //Botón Limpiar cuando el mouse entre
    private void btnTextLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextLimpiarMouseEntered
        if (pressed) {
            btnLimpiar.setBackground(new Color(0, 121, 107));
            btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnTextLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        } else {
            btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnTextLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnTextLimpiarMouseEntered

    //Botón Limpiar cuando el mouse sale
    private void btnTextLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextLimpiarMouseExited
        if (pressed) {
            btnLimpiar.setBackground(new Color(0, 150, 136));
        } else {
            btnLimpiar.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnTextLimpiarMouseExited

    //Botón Limpiar al ser clickeado
    private void btnTextLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextLimpiarMouseClicked
        background.requestFocusInWindow();
        pressed = false;
        aggPressed = false;
        mostrados = false;
        mostradoGet = true;
        mostradosFin = true;

        entryField.setEditable(true);
        /*btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnTextContinuar.setForeground(GRAY);
        
        elementAddedLabel.setText("");
        listDisplayText.setText("");

        btnTextObtener.setForeground(WHITE);
        getElementLabel.setText("");
        getElementEntry.setText("");
        getElementEntry.setEnabled(false);
        getElementEntry.setEditable(true);
        getElementEntry.setForeground(GRAY);
        dsplayGetElement.setText("");
        separatorgetElement.setForeground(WHITE);
        btnObtener.setBackground(WHITE);

        btnTextDeleteElement.setForeground(WHITE);
        deleteElementLabel.setText("");
        deleteElementEntry.setText("");
        deleteElementEntry.setEnabled(false);
        deleteElementEntry.setEditable(true);
        deleteElementEntry.setForeground(GRAY);
        dsplayDeleteElement.setText("");
        separatorDeleteElement.setForeground(WHITE);
        btnDeleteElement.setBackground(WHITE);

        labelSortMay.setText("");
        labelSortMen.setText("");*/
        clear();
        btnTextLimpiar.setForeground(new java.awt.Color(128, 128, 128));
        dsplaySortMayText.setText("");
        dsplaySortMenText.setText("");

        lista1 = new ListaEnlazada();
        lista2 = new ListaEnlazada();
        lista3 = new ListaEnlazada();
    }//GEN-LAST:event_btnTextLimpiarMouseClicked

    //Botón Obtener cuando el mouse entre
    private void btnTextObtenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextObtenerMouseEntered
        boolean isNadaPresionado = !pressed && !aggPressed;
        boolean isAggPressed = !pressed && aggPressed;
        boolean isGetDisplayed = mostradoGet;

        if (isNadaPresionado) {
            btnObtener.setBackground(WHITE);
            btnTextObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        } else if (isAggPressed) {
            btnTextObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnObtener.setBackground(WHITE);
        } else if (!isGetDisplayed) {
            btnTextObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        } else {
            btnTextObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnObtener.setBackground(new java.awt.Color(0, 121, 107));
        }
    }//GEN-LAST:event_btnTextObtenerMouseEntered

    //Botón Limpiar cuando el mouse sale
    private void btnTextObtenerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextObtenerMouseExited
        boolean isNadaPresionado = !pressed && !aggPressed;
        boolean isAggPressed = !pressed && aggPressed;
        boolean isGetDisplayed = mostradoGet;

        if (isNadaPresionado) {
            btnObtener.setBackground(WHITE);
        } else if (isAggPressed) {
            btnObtener.setBackground(WHITE);
        } else if (!isGetDisplayed) {
            btnTextObtener.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        } else {
            btnObtener.setBackground(new java.awt.Color(0, 150, 136));
        }
    }//GEN-LAST:event_btnTextObtenerMouseExited

    //Botón Obtener al ser clickeado
    private void btnTextObtenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextObtenerMouseClicked
        background.requestFocusInWindow();
        boolean isAllPressed = pressed && aggPressed && mostradoGet;

        if (isAllPressed) {
            try {
                int index = Integer.parseInt(getElementEntry.getText());
                dsplayGetElement.setText("El elemento es " + lista1.get(index));
                mostradoGet = false;
                btnObtener.setBackground(new Color(204, 204, 204));
                btnTextObtener.setForeground(GRAY);
                //getElementEntry.setEditable(false);
            } catch (NullPointerException indexNull) {
                int size = lista1.getSize();
                if (lista1.getSize() == 1) {
                    dsplayGetElement.setText("Solo se puede ingresar la posición 0");
                } else {
                    dsplayGetElement.setText("Posición no valida , solo valores desde 0 hasta " + (size - 1));
                }
            } catch (NumberFormatException valueNotValid) {
                int size = lista1.getSize();
                if (size == 1) {
                    dsplayGetElement.setText("Valor no valido, solo se puede ingresar la posición 0");
                } else {
                    dsplayGetElement.setText("Valor no valido, ingresa un valor númerico desde 0 hasta " + (size - 1));
                }
            }
        }
    }//GEN-LAST:event_btnTextObtenerMouseClicked

    //Botón Eliminar cuando el mouse entre
    private void btnTextDeleteElementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextDeleteElementMouseEntered
        boolean isNothingPressed = !pressed && !aggPressed;
        boolean isAggPressed = !pressed && aggPressed;
        boolean isFinDisplayed = mostradosFin;

        if (isNothingPressed) {
            btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnDeleteElement.setBackground(WHITE);
        } else if (isAggPressed) {
            btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnDeleteElement.setBackground(WHITE);
        } else if (!isFinDisplayed) {
            btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        } else {
            btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnDeleteElement.setBackground(new java.awt.Color(0, 121, 107));
        }
    }//GEN-LAST:event_btnTextDeleteElementMouseEntered

    //Botón Eliminar cuando el mouse salga
    private void btnTextDeleteElementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextDeleteElementMouseExited
        boolean isNothingPressed = !pressed && !aggPressed;
        boolean isAggPressed = !pressed && aggPressed;
        boolean isFinDisplayed = mostradosFin;

        if (isNothingPressed) {
            btnDeleteElement.setBackground(WHITE);
        } else if (isAggPressed) {
            btnDeleteElement.setBackground(WHITE);
        } else if (!isFinDisplayed) {
            btnTextDeleteElement.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        } else {
            btnDeleteElement.setBackground(new java.awt.Color(0, 150, 136));
        }
    }//GEN-LAST:event_btnTextDeleteElementMouseExited

    //Botón Eliminar al ser clickeado
    private void btnTextDeleteElementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTextDeleteElementMouseClicked
        background.requestFocusInWindow();
        boolean isAllPressed = pressed && aggPressed && mostradosFin;

        if (isAllPressed) {

            try {
                int index = Integer.parseInt(deleteElementEntry.getText());
                elementAddedLabel.setText("Lista Actualizada");
                lista1.delete(index);
                lista2.delete(index);
                lista3.delete(index);

                Nodo actual = lista1.head;
                listDisplayText.setText("");
                while (actual != null) {
                    int valor = actual.getValor();
                    listDisplayText.append(Integer.toString(valor) + " ");
                    actual = actual.getSiguiente();
                }
                dsplayDeleteElement.setText("Elemento " + deleteElementEntry.getText() + " Eliminado");

                labelSortMay.setText("Elementos ordenados de mayor a menor");
                lista2.sortMayor();
                if (lista2.getSize() == 1) {
                    dsplaySortMayText.setText(Integer.toString(lista2.get(0)));
                } else {
                    dsplaySortMayText.setText("");
                    Nodo actual2 = lista2.head;
                    while (actual2 != null) {
                        int valor2 = actual2.getValor();
                        dsplaySortMayText.append(Integer.toString(valor2) + " ");
                        actual2 = actual2.getSiguiente();
                    }
                }

                labelSortMen.setText("Elementos ordenados de menor a mayor");
                lista3.sortMenor();
                if (lista3.getSize() == 1) {
                    dsplaySortMenText.setText(Integer.toString(lista2.get(0)));
                } else {
                    dsplaySortMenText.setText("");
                    Nodo actual3 = lista3.head;
                    while (actual3 != null) {
                        int valor3 = actual3.getValor();
                        dsplaySortMenText.append(Integer.toString(valor3) + " ");
                        actual3 = actual3.getSiguiente();
                    }
                }

                btnDeleteElement.setBackground(new Color(204, 204, 204));
                btnTextDeleteElement.setForeground(GRAY);
                mostradosFin = false;
                //deleteElementEntry.setEditable(false);

                if (lista1.getSize() == 0) {
                    elementAddedLabel.setText("Lista vacia");
                }
            } catch (NullPointerException indexNull) {
                int size = lista1.getSize();
                elementAddedLabel.setText("Lista Generada");
                if (size == 0) {
                    dsplayDeleteElement.setText("Lista vacia");
                    elementAddedLabel.setText("Lista vacia");
                } else if (size == 1) {
                    dsplayDeleteElement.setText("Solo se puede ingresar la posición 0");
                } else {
                    dsplayDeleteElement.setText("Posición no valida , solo valores desde 0 hasta " + (size - 1));
                }

            } catch (NumberFormatException valueNotValid) {
                int size = lista1.getSize();
                elementAddedLabel.setText("Lista Generada");
                if (size == 0) {
                    dsplayDeleteElement.setText("Lista vacia");
                    elementAddedLabel.setText("Lista vacia");
                } else if (size == 1) {
                    dsplayDeleteElement.setText("Valor no valido, solo se puede ingresar la posición 0");
                } else {
                    dsplayDeleteElement.setText("Valor no valido, ingresa un valor númerico desde 0 hasta " + (size - 1));
                }

            }
        }


    }//GEN-LAST:event_btnTextDeleteElementMouseClicked

    //Entrada de numeros al ser presionada
    //TODO CREAR EVENTO  FOCUS LOST CON btnagregar
    private void entryFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryFieldMousePressed
        if (entryField.getText().equals("Ingresa un número") && entryField.isEditable()) {
            entryField.setText("");
            entryField.setForeground(BLACK);
            //elementAddedLabel.setText("");
        }
    }//GEN-LAST:event_entryFieldMousePressed

    //Entrada de Obtener elemento al ser presionada
    private void getElementEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getElementEntryMousePressed
        if (getElementEntry.getText().equals("Ingresa la posición")) {
            getElementEntry.setText("");
            getElementEntry.setForeground(BLACK);
        }
        if (deleteElementEntry.getText().isEmpty() && getElementEntry.isEnabled()) {
            deleteElementEntry.setText("Ingresa la posición");
            deleteElementEntry.setForeground(GRAY);
        }
    }//GEN-LAST:event_getElementEntryMousePressed

    //Entrada de Eliminar elemento al ser presionada
    private void deleteElementEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteElementEntryMousePressed
        if (deleteElementEntry.getText().equals("Ingresa la posición")) {
            deleteElementEntry.setText("");
            deleteElementEntry.setForeground(BLACK);
        }
        if (getElementEntry.getText().isEmpty() && getElementEntry.isEnabled()) {
            getElementEntry.setText("Ingresa la posición");
            getElementEntry.setForeground(GRAY);
        }

    }//GEN-LAST:event_deleteElementEntryMousePressed

    //Entrada de numeros cuando el mouse sale
    private void entryFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryFieldMouseExited
        if ((!"Ingresa un número".equals(entryField.getText())) && (!"".equals(entryField.getText()))) {
            btnAgregar.setBackground(new java.awt.Color(0, 150, 136));
            btnTextAgregar.setForeground(WHITE);
        }
    }//GEN-LAST:event_entryFieldMouseExited

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        background.requestFocusInWindow();
    }//GEN-LAST:event_backgroundMouseClicked

    public void clear() {
        elementAddedLabel.setText("Elemento Agregado");
        elementAddedLabel.setVisible(false);

        getElementLabel.setVisible(false);
        getElementEntry.setVisible(false);
        separatorgetElement.setVisible(false);
        btnTextObtener.setForeground(new java.awt.Color(255, 255, 255));
        btnObtener.setVisible(false);

        deleteElementLabel.setVisible(false);
        deleteElementEntry.setVisible(false);
        separatorDeleteElement.setVisible(false);
        btnDeleteElement.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteElement.setVisible(false);

        labelSortMay.setVisible(false);
        labelSortMen.setVisible(false);

        listDisplayText.setText("");
        dsplayGetElement.setText("");
        dsplayDeleteElement.setText("");
        dsplaySortMayText.setText("");
        dsplaySortMenText.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eval3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eval3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eval3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eval3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eval3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnContinuar;
    private javax.swing.JPanel btnDeleteElement;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnObtener;
    private javax.swing.JLabel btnTextAgregar;
    private javax.swing.JLabel btnTextContinuar;
    private javax.swing.JLabel btnTextDeleteElement;
    public javax.swing.JLabel btnTextLimpiar;
    private javax.swing.JLabel btnTextObtener;
    private javax.swing.JTextField deleteElementEntry;
    private javax.swing.JLabel deleteElementLabel;
    private javax.swing.JLabel dsplayDeleteElement;
    private javax.swing.JLabel dsplayGetElement;
    private javax.swing.JScrollPane dsplaySortMay;
    private javax.swing.JTextArea dsplaySortMayText;
    private javax.swing.JScrollPane dsplaySortMen;
    private javax.swing.JTextArea dsplaySortMenText;
    private javax.swing.JLabel elementAddedLabel;
    private javax.swing.JTextField entryField;
    private javax.swing.JTextField getElementEntry;
    private javax.swing.JLabel getElementLabel;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JLabel labelSortMay;
    private javax.swing.JLabel labelSortMen;
    private javax.swing.JScrollPane listDisplay;
    public javax.swing.JTextArea listDisplayText;
    private javax.swing.JSeparator separatorDeleteElement;
    private javax.swing.JSeparator separatorEntry;
    private javax.swing.JSeparator separatorgetElement;
    // End of variables declaration//GEN-END:variables

}
